using Azure.Storage.Queues;
using System.Text;

const string connectionString = "UseDevelopmentStorage=true";
const string queueName = "orders";

var queueServiceClient = new QueueServiceClient(connectionString);
var queueClient = queueServiceClient.GetQueueClient(queueName);

await queueClient.CreateIfNotExistsAsync();

const string message = "New order generated by the QueueUploader!";

Console.WriteLine($"Sending message to the '{queueName}' queue...");

var plainTextBytes = Encoding.UTF8.GetBytes(message);
var base64Message = Convert.ToBase64String(plainTextBytes);

await queueClient.SendMessageAsync(base64Message);

Console.WriteLine("Upload complete! Check the Azure Functions log.");