using System.Net;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Http;
using Microsoft.Extensions.Logging;

namespace AzureFunctionsCookbook.Bindings.Queue;

public class QueueOutputBindingExample
{
    private readonly ILogger<QueueOutputBindingExample> _logger;

    public QueueOutputBindingExample(ILogger<QueueOutputBindingExample> logger)
    {
        _logger = logger;
    }

    [Function(nameof(QueueOutputBindingExample))]
    public async Task<QueueOutputResponse> Run(
        [HttpTrigger(AuthorizationLevel.Function, "post", Route = "queue-output")] HttpRequestData req)
    {
        _logger.LogInformation("📥 Receiving HTTP request to send a message to the queue.");

        string requestBody = await new StreamReader(req.Body).ReadToEndAsync();
        string messageContent = string.IsNullOrWhiteSpace(requestBody) 
            ? "Default message generated by Queue Output Binding." 
            : requestBody;

        var response = req.CreateResponse(HttpStatusCode.Created);
        await response.WriteStringAsync("Message successfully sent to the 'orders' queue!");

        return new QueueOutputResponse
        {
            HttpResponse = response,
            QueueMessage = messageContent
        };
    }
}

public class QueueOutputResponse
{
    [QueueOutput("orders")]
    public string? QueueMessage { get; set; }
    [HttpResult]
    public HttpResponseData? HttpResponse { get; set; }
}