using System.Net;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Http;
using Microsoft.Extensions.Logging;

namespace AzureFunctionsCookbook.Bindings.Blob;

public class BlobOutputBindingExample
{
    private readonly ILogger<BlobOutputBindingExample> _logger;

    public BlobOutputBindingExample(ILogger<BlobOutputBindingExample> logger)
    {
        _logger = logger;
    }

    [Function(nameof(BlobOutputBindingExample))]
    public async Task<BlobOutputResponse> Run(
        [HttpTrigger(AuthorizationLevel.Function, "post", Route = "blob-output/{fileName}")] HttpRequestData req,
        string fileName)
    {
        _logger.LogInformation("📥 Receiving HTTP request to create: {fileName}", fileName);

        string requestBody = await new StreamReader(req.Body).ReadToEndAsync();
        string fileContent = string.IsNullOrWhiteSpace(requestBody) 
            ? "Content generated by HTTP Output Binding." 
            : requestBody;

        var response = req.CreateResponse(HttpStatusCode.Created);
        await response.WriteStringAsync($"File '{fileName}' generated in the 'uploads' container!");

        return new BlobOutputResponse
        {
            HttpResponse = response,
            BlobData = fileContent
        };
    }
}

public class BlobOutputResponse
{
    [BlobOutput("uploads/{fileName}")]
    public string BlobData { get; set; }
    
    public HttpResponseData HttpResponse { get; set; }
}