using Azure.Messaging.ServiceBus;

// NOTE: Replace with your real Service Bus connection string from the Azure portal.
// Service Bus does not use Azurite (UseDevelopmentStorage=true).
const string connectionString = "Endpoint=sb://SEU-NAMESPACE.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SUA_CHAVE_AQUI";
const string queueName = "orders";

Console.WriteLine($"Conectando ao Service Bus e preparando para enviar para a fila '{queueName}'...");

await using var client = new ServiceBusClient(connectionString);

await using var sender = client.CreateSender(queueName);

const string messageBody = "New order generated by the ServiceBusUploader!";

var message = new ServiceBusMessage(messageBody);

Console.WriteLine("Enviando mensagem...");

await sender.SendMessageAsync(message);

Console.WriteLine("Upload concluído! Verifique os logs da sua Azure Function.");